# Generated by Django 5.0 on 2023-12-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('organizer', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('county', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('organizer', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
