# Generated by Django 5.0 on 2024-02-16 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('short_description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('latest', 'Latest'), ('reviews', 'Past Event Reviews'), ('upcoming', 'Upcoming Events Reviews'), ('tech', 'Tech in the Entertainment Industry'), ('artists', "Artist's Corner")], default=[('latest', 'Latest'), ('reviews', 'Past Event Reviews'), ('upcoming', 'Upcoming Events Reviews'), ('tech', 'Tech in the Entertainment Industry'), ('artists', "Artist's Corner")], max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('upcoming', 'Upcoming Events'), ('past', 'Past Event')], default=[('upcoming', 'Upcoming Events'), ('past', 'Past Event')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
