# Generated by Django 5.0 on 2024-02-04 02:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='category_type',
            field=models.CharField(choices=[('upcoming', 'Upcoming Events'), ('past', 'Past Event')], default=[('upcoming', 'Upcoming Events'), ('past', 'Past Event')], max_length=50),
        ),
    ]
