# Generated by Django 5.0 on 2023-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_organizer_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
