# Generated by Django 5.0 on 2024-02-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_description_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='currentevent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='event',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('blog_author', 'Blog Author'), ('event_organizer', 'Event Organizer')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.customuser'),
        ),
        migrations.DeleteModel(
            name='CurrentEvent',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
