# Generated by Django 5.0 on 2023-12-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organizer_email_organizer_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
