# Generated by Django 5.0 on 2024-02-17 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cartItem_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
