# Generated by Django 5.0 on 2024-02-18 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_cartitem_cart_remove_cartitem_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
