# Generated by Django 5.0 on 2023-12-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
