# Generated by Django 5.0 on 2023-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
