# Generated by Django 5.0 on 2024-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_blog_category_type_event_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_type',
            field=models.CharField(choices=[('latest', 'Latest'), ('event_reviews', 'Event Reviews'), ('upcoming_events', 'Upcoming Events Reviews'), ('tech_entertainment', 'Tech in the Entertainment Industry'), ('artists_corner', "Artist's Corner")], default=[('latest', 'Latest'), ('event_reviews', 'Event Reviews'), ('upcoming_events', 'Upcoming Events Reviews'), ('tech_entertainment', 'Tech in the Entertainment Industry'), ('artists_corner', "Artist's Corner")], max_length=50),
        ),
    ]
