# Generated by Django 5.0 on 2024-01-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_created_at_blog_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=[('latest', 'Latest'), ('event_reviews', 'Event Reviews'), ('upcoming_events', 'Upcoming Events Reviews'), ('tech_entertainment', 'Tech in the Entertainment Industry'), ('artists_corner', "Artist's Corner")], max_length=50),
        ),
    ]
