# Generated by Django 5.0 on 2024-02-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_profile_is_author_profile_is_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='profile',
            name='function',
            field=models.CharField(blank=True, choices=[('Author', 'Author'), ('Organizer', 'Organizer')], max_length=20),
        ),
    ]
