# Generated by Django 5.0 on 2024-02-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_profile_is_author_remove_profile_is_organizer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='function',
            new_name='func',
        ),
    ]
