# Generated by Django 5.0 on 2024-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('new', 'Latest'), ('past_event_reviews', 'Past Event Reviews'), ('upcoming_events', 'Upcoming Events Reviews'), ('tech_entertainment', 'Tech in the Entertainment Industry'), ('artists_corner', "Artist's Corner")], default=[('new', 'Latest'), ('past_event_reviews', 'Past Event Reviews'), ('upcoming_events', 'Upcoming Events Reviews'), ('tech_entertainment', 'Tech in the Entertainment Industry'), ('artists_corner', "Artist's Corner")], max_length=50),
        ),
    ]
