# Generated by Django 5.0 on 2024-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('latest', 'Latest'), ('reviews', 'Past Event Reviews'), ('upcoming', 'Upcoming Events Reviews'), ('tech', 'Tech in the Entertainment Industry'), ('artists', "Artist's Corner")], default=[('latest', 'Latest'), ('reviews', 'Past Event Reviews'), ('upcoming', 'Upcoming Events Reviews'), ('tech', 'Tech in the Entertainment Industry'), ('artists', "Artist's Corner")], max_length=50),
        ),
    ]
