# Generated by Django 5.0 on 2024-02-03 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
