# Generated by Django 5.0 on 2024-02-03 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
    ]
