# Generated by Django 5.0 on 2024-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
